### ISSUE TITLE
Vimeo Player Question

### ISSUE THREAD

**Issue by craigpetrou** [bdougherty/ama#1]
I have two links on a page which pop ups open a Bootstrap 3 modal.

I would like to be able to have the videos work independently from each other.

I would like to be able to click one link, have the video open in a modal and auto start (only when the modal is open and not when the page is first loaded).

I would also like to be able to close the modal and that particular video stops playing (it currently keeps playing in the background even if it isn't visible on the screen or I attempt to run a different video).

Any help, or direction, would be greatly appreciated.

**Comment by craigpetrou** [comment]
Oh, I almost forgot... I{ would like the video to be responsive to the different screen sizes. (Bootstrap)

**Comment by bdougherty** [comment]
Oops, not sure how I missed this. I no longer work for Vimeo, but check out the [player js library](https://github.com/vimeo/player.js) that I wrote while I was still there. It will let you control the player.
